#pragma once

#define FOOTER_HEIGHT 1
#define HEADER_HEIGHT 1
#define MSG_BUS_WIDTH 35

#define COLOR_GREY 50
#define COLOR_DARK_GREY 51

#define STD_COLOR_PAIR 1
#define HEADER_COLOR_PAIR 99
#define FOOTER_COLOR_PAIR 98
#define MSG_BUS_COLOR_PAIR 97
#define HIGHLIGHT_EXPR_COLOR_PAR 96