#pragma once

#define ARCHIVE_X_PADDING 5
#define ARCHIVE_Y_PADDING 2

#define REPLACE_WITH_ID_THRESHOLD 15

#define FOOTER_HEIGHT 1
#define HEADER_HEIGHT 1
#define QUEUE_WIDTH (REPLACE_WITH_ID_THRESHOLD + 1)
#define POPUP_WIDTH 60
#define POPUP_HEIGHT 12

#define COLOR_GREY 50
#define COLOR_LIGHT_GREY 52

#define STD_COLOR_PAIR 1
#define HEADER_COLOR_PAIR 99
#define FOOTER_COLOR_PAIR 98
#define HIGHLIGHT_EXPR_COLOR_PAR 96
#define MUTED_COLOR_PAIR 95
#define AMBIGUOUS_COLOR_PAIR 94
#define POPUP_COLOR_PAIR HEADER_COLOR_PAIR

#define A_HIGHLIGHT (A_STANDOUT | COLOR_PAIR(HIGHLIGHT_EXPR_COLOR_PAR))
#define A_AMBIGUOUS COLOR_PAIR(AMBIGUOUS_COLOR_PAIR)
#define A_MUTED COLOR_PAIR(MUTED_COLOR_PAIR)

#define PAD_HEIGHT_MULTIPLIER 100

#define KEY_ESCAPE 27
#define KEY_ARROW_UP KEY_UP
#define KEY_ARROW_DOWN KEY_DOWN

#define EVENT_COUNTER_TEXT "Event: %3d"
#define MULTIPLIER_TEXT "%dx"
#define FOOTER_QUICK_ACTIONS_TEXT "q: quit    n: next    p: previous    o: toggle opers    h: help"
#define FOOTER_WAIT_FOR_MARKER_TEXT "Input marker or press <esc>"